version: '3.1'

services:
  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: bJ3@RnXi*m
      MYSQL_DATABASE: server_snitch
      MYSQL_USER: monitor
      MYSQL_PASSWORD: bJ3@RnXi*m
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8080:80"
  grafana:
    image: grafana/grafana
    container_name: grafana
    links:
      - database
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
volumes:
  dbdata:
  grafana-data: